version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/joway/imagic
    steps:
      - checkout
      - run: sudo apt update && sudo apt install -y gcc
      - run: ./dep.sh
      - run: mkdir -p ./output
      - run: env GO111MODULE=on go build
      - run: ./imagic compress --quality 70 --parallel 10 --suffix .comp --output ./testdata/output ./testdata/images/**/*.png
      - run: ./imagic compress --quality 70 --parallel 10 --suffix .comp --output ./testdata/output ./testdata/images/**/*.jpg
      - run: ./imagic resize --width 320 --parallel 10 --suffix .res --output ./testdata/output ./testdata/images/**/*.png
      - run: ./imagic resize --width 320 --parallel 10 --suffix .res --output ./testdata/output ./testdata/images/**/*.jpg
      - run: ./imagic watermark -t ./testdata/images/texture.png -p 10 -o ./output ./testdata/**/*.jpg
      - run: env GO111MODULE=on go test -race -coverprofile=coverage.txt -covermode=atomic -v ./...
      - run: bash <(curl -s https://codecov.io/bash)
  install:
    docker:
      - image: circleci/golang:1.11
    steps:
      - run: mkdir -p ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
      - run: go get github.com/joway/imagic
      - run: imagic version
workflows:
  version: 2
  pipeline:
    jobs:
      - build
      - install
